controller_manager:
  ros__parameters:
   update_rate : 1000 #Hz
   use_sim_time : true

   joint_state_broadcaster:
    type : joint_state_broadcaster/JointStateBroadCaster
    
   position_controller:
    type: position_controllers/JointGroupPositionController
    
   velocity_controller:
    type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    joints:
      - leg_front_left_joint
      - leg_front_right_joint
    interface_name: position
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity



velocity_controller:
  ros__parameters:
    joints:
      - wheel_front_left_joint
      - wheel_front_right_joint
    interface_name : velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    update_rate : 1000
    use_sim_time : true
    


    
  
