<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

     <xacro:include filename="inertial_macros.xacro" />

    <xacro:property name="chassis_length" value="1.3"/>
    <xacro:property name="chassis_width" value="1.0"/>
    <xacro:property name="chassis_height" value="0.3"/>
    <xacro:property name="chassis_mass" value="3.0"/>

    <xacro:property name="leg_length" value="0.1"/>
    <xacro:property name="leg_width" value="0.1"/>
    <xacro:property name="leg_height" value="0.7"/>
    <xacro:property name="leg_mass" value="0.5"/>

    <xacro:property name="leg_offset_x" value="1.0"/>
    <xacro:property name="leg_offset_y" value="0.5"/>
    <xacro:property name="leg_offset_z" value="0.1"/>

    <xacro:property name="wheel_radius" value="0.25"/>
    <xacro:property name="wheel_thickness" value="0.1"/>
    <xacro:property name="wheel_mass" value="0.5"/>

    <xacro:property name="wheel_offset_x" value="1.0"/>
    <xacro:property name="wheel_offset_y" value="0.5"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    
    
    <xacro:property name="caster_wheel_offset_x" value="0.350"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <!-- BASE_FOOTPRINT LINK -->


    <link name="base_footprint"/>
        <!-- <origin xyz="-11.66 7.628 0" rpy="0.1 0.2 0.3" />
         <pose>-11.66 7.628 0 0 0 0</pose> -->


    <!-- <pose>-11.66 7.628 0 0 0 0</pose> -->
    


   <!-- BASE LINK -->

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.7"/>
    </joint>

    <link name="base_link">
       
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

  

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="left_leg_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0 -0.35" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
        <disable_collision>0</disable_collision>
        
    </joint>

    <joint name="left_wheel_leg_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_leg_link"/>
        <origin xyz="${leg_offset_x} ${leg_offset_y} ${-leg_offset_z}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        
    </joint>

    <!-- Left leg link -->
    <link name="left_leg_link">
        <visual>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${leg_length}" y="${leg_width}" z="${leg_height}">
            <origin xyz="${leg_length/2} 0 ${leg_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

   




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="right_leg_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 0 -0.35" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
        <disable_collision>0</disable_collision>
    </joint>

    <joint name="right_wheel_leg_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_leg_link"/>
        <origin xyz="${leg_offset_x} ${-leg_offset_y} ${-leg_offset_z}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        
    </joint>

    <!-- Right leg link -->
    <link name="right_leg_link">
         <visual>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${leg_length}" y="${leg_width}" z="${leg_height}">
            <origin xyz="${leg_length/2} 0 ${leg_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

   


     <!-- wheel back right-->

<joint name="wheel_back_right_joint" type="continuous">

    <parent link="right_back_leg_link"/>
    <child link="wheel_back_right"/>
      <origin xyz="0 0 -0.35" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <disable_collision>0</disable_collision>

</joint>

<joint name="right_wheel_back_leg_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_back_leg_link"/>
        <origin xyz="${caster_wheel_offset_x} ${-wheel_offset_y} ${-leg_offset_z}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
        
    </joint>

    <!-- Right back leg link -->
    <link name="right_back_leg_link">
         <visual>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${leg_length}" y="${leg_width}" z="${leg_height}">
            <origin xyz="${leg_length/2} 0 ${leg_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

<link name="wheel_back_right">
    <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
</link>



<!-- wheel back left-->
<joint name="wheel_back_left_joint" type="continuous">

    <parent link="left_back_leg_link"/>
    <child link="wheel_back_left"/>
      <origin xyz="0 0 -0.35" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
    <disable_collision>0</disable_collision>

</joint>

<joint name="left_wheel_back_leg_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_back_leg_link"/>
        <origin xyz="${caster_wheel_offset_x} ${wheel_offset_y} ${-leg_offset_z}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 0 1"/>
        
    </joint>

    <!-- left back leg link -->
    <link name="left_back_leg_link">
         <visual>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${leg_length} ${leg_width} ${leg_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${leg_length}" y="${leg_width}" z="${leg_height}">
            <origin xyz="${leg_length/2} 0 ${leg_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

<link name="wheel_back_left">
    <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
</link>







</robot>